import {formCSS} from './form-ui.js';
const escape=text=>String(text).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export function renderWebForm(definition){
  const publicFields=definition.fields.map(({id,label,kind,required,choices,minLength,maxLength})=>({id,label,kind,required:required===true,choices,minLength,maxLength}));
  const encoded=JSON.stringify(publicFields).replaceAll('<','\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029');
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(definition.title)}</title><style>${formCSS}.tg-form-dialog{margin:24px auto;max-height:none;border:0}body{margin:0;background:#edf5f2}h1{font-size:24px}</style></head><body><main class="tg-form-dialog"><h1>${escape(definition.title)}</h1><p>Antworten werden auf dem freigebenden Gerät in der Tabelle gespeichert.</p><form id="form"><div id="fields"></div><button type="submit">Antwort senden</button></form><p id="status" role="status" aria-live="polite"></p><small>Lokale Freigabe · tinyDatagrid</small></main><script>
const fields=${encoded};
const form=document.querySelector('#form'),status=document.querySelector('#status');let pending=null;
for(const field of fields){const label=document.createElement('label');label.textContent=field.label+(field.required?' *':'');let input;
if(['list','boolean'].includes(field.kind)){input=document.createElement('select');for(const [value,text] of [['','Bitte wählen'],...(field.kind==='boolean'?[['true','Ja'],['false','Nein']]:field.choices.map(value=>[value,value]))]){const option=document.createElement('option');option.value=value;option.textContent=text;input.append(option);}}
else{input=document.createElement(field.kind==='textarea'?'textarea':'input');if(input.tagName==='INPUT')input.type=['email','tel','url','date','time'].includes(field.kind)?field.kind:'text';if(['number','integer'].includes(field.kind))input.inputMode=field.kind==='integer'?'numeric':'decimal';if(field.kind==='time')input.step='0.001';}
input.name=field.id;input.required=field.required;input.maxLength=field.maxLength??10000;if(field.minLength!=null)input.minLength=field.minLength;if(['email','url'].includes(field.kind)){input.autocapitalize='none';input.spellcheck=false;}input.autocomplete=({email:'email',tel:'tel',url:'url'})[field.kind]||'off';label.append(input);document.querySelector('#fields').append(label);}
form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');if(button.disabled)return;const values=Object.fromEntries(new FormData(form));const content=JSON.stringify(values);if(!pending||pending.content!==content)pending={content,id:globalThis.crypto?.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('')};button.disabled=true;status.textContent='Wird gespeichert …';try{const response=await fetch(location.pathname+'submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestID:pending.id,values}),cache:'no-store'});const result=await response.json();if(!response.ok||!result.saved)throw new Error(result.error||'Die Antwort wurde nicht bestätigt.');pending=null;form.reset();status.textContent='Antwort gespeichert. Du kannst eine weitere Antwort senden.';status.classList.remove('tg-form-error');}catch(error){status.textContent=error.message+' Du kannst dieselbe Antwort erneut senden. Prüfe, ob die App und Freigabe noch geöffnet sind.';status.classList.add('tg-form-error');}finally{button.disabled=false;}};
</script></body></html>`;
}
