import { formulaHelpRows } from "./formula-help-data.js";

// One record per operation. Translations resolve to IDs before evaluation;
// they never create another implementation or rewrite formula text literals.
const legacy = {
  AVG: "AVERAGE",
  POWER: "POW",
  INT: "FLOOR",
  SUBSTRING: "SUBSTR",
  REGEXTEST: "REGEXP",
  REGEXMATCH: "REGEXP",
  REGEXEXTRACT: "REGEXP_EXTRACT",
  REGEXREPLACE: "REGEXP_REPLACE",
  SVERWEIS: "VLOOKUP",
  WVERWEIS: "HLOOKUP",
  XVERWEIS: "XLOOKUP",
  VERGLEICH: "MATCH",
  VERWEIS: "LOOKUP",
  WEBSERVICE: "WEB.GET",
};
// EN segment | DE | FR | IT. Technical standards (JSON, RGB, SHA256, …)
// deliberately keep their established spelling across languages.
const translations = `
CREATE|ERSTELLEN|CRÉER|CREA
SECONDS|SEKUNDEN|SECONDES|SECONDI
DECIMAL|DEZIMAL|DÉCIMAL|DECIMALE
SUBTRACT|SUBTRAHIEREN|SOUSTRAIRE|SOTTRAI
MULTIPLY|MULTIPLIZIEREN|MULTIPLIER|MOLTIPLICA
DIVIDE|DIVIDIEREN|DIVISER|DIVIDI
NUMBER|ZAHL|NOMBRE|NUMERO
SUM|SUMME|SOMME|SOMMA
AVERAGE|MITTELWERT|MOYENNE|MEDIA
MIN|MIN|MIN|MIN
MAX|MAX|MAX|MAX
MEDIAN|MEDIAN|MÉDIANE|MEDIANA
LARGE|KGRÖSSTE|GRANDE_VALEUR|GRANDE
SMALL|KKLEINSTE|PETITE_VALEUR|PICCOLO
COUNT|ANZAHL|NB|CONTA_NUMERI
COUNTA|ANZAHL_WERTE|NBVAL|CONTA_VALORI
COUNTBLANK|ANZAHL_LEER|NB_VIDE|CONTA_VUOTE
ABS|ABS|ABS|ASS
ROUND|RUNDEN|ARRONDI|ARROTONDA
ROUNDUP|AUFRUNDEN|ARRONDI_SUP|ARROTONDA_ECCESSO
ROUNDDOWN|ABRUNDEN|ARRONDI_INF|ARROTONDA_DIFETTO
FLOOR|GANZZAHL_AB|ENTIER_INF|INTERO_INFERIORE
CEIL|GANZZAHL_AUF|ENTIER_SUP|INTERO_SUPERIORE
SQRT|WURZEL|RACINE|RADICE
POW|POTENZ|PUISSANCE|POTENZA
MOD|REST|MOD|RESTO
SIGN|VORZEICHEN|SIGNE|SEGNO
IF|WENN|SI|SE
IFS|WENNS|SI_MULTIPLE|SE_MULTIPLO
SWITCH|FALL|SELON|CASO
CHOOSE|WAHL|CHOISIR|SCEGLI
IFERROR|WENNFEHLER|SIERREUR|SE_ERRORE
IFNA|WENNNV|SI_NON_DISP|SE_NON_DISP
AND|UND|ET|E
OR|ODER|OU|O
XOR|EXKLUSIV_ODER|OU_EXCLUSIF|O_ESCLUSIVO
NOT|NICHT|NON|NON
TRUE|WAHR|VRAI|VERO
FALSE|FALSCH|FAUX|FALSO
ISBLANK|ISTLEER|ESTVIDE|VAL_VUOTO
ISNUMBER|ISTZAHL|ESTNUM|VAL_NUMERO
ISTEXT|ISTTEXT|ESTTEXTE|VAL_TESTO
ISLOGICAL|ISTLOGISCH|ESTLOGIQUE|VAL_LOGICO
ISERROR|ISTFEHLER|ESTERREUR|VAL_ERRORE
N|ZAHL|NOMBRE|NUMERO
VALUE|ZAHLWERT|VALEUR|VALORE
CONCAT|VERKETTEN|CONCAT|CONCATENA
LEN|LÄNGE|NBCAR|LUNGHEZZA
TEXTJOIN|TEXTVERBINDEN|JOINDRE_TEXTE|UNISCI_TESTO
UPPER|GROSS|MAJUSCULE|MAIUSCOLO
LOWER|KLEIN|MINUSCULE|MINUSCOLO
PROPER|GROSS_ANFANG|NOMPROPRE|MAIUSCOLO_INIZIALE
LEFT|LINKS|GAUCHE|SINISTRA
RIGHT|RECHTS|DROITE|DESTRA
MID|TEIL|STXT|STRINGA_ESTRAI
FIND|FINDEN|TROUVE|TROVA
SEARCH|SUCHEN|CHERCHE|CERCA
SUBSTITUTE|WECHSELN|SUBSTITUE|SOSTITUISCI
REPLACE|ERSETZEN|REMPLACER|RIMPIAZZA
TEXT|TEXT|TEXTE|TESTO
SUMIF|SUMMEWENN|SOMME_SI|SOMMA_SE
COUNTIF|ZÄHLENWENN|NB_SI|CONTA_SE
AVERAGEIF|MITTELWERTWENN|MOYENNE_SI|MEDIA_SE
SUMIFS|SUMMEWENNS|SOMME_SI_MULTIPLE|SOMMA_SE_MULTIPLO
COUNTIFS|ZÄHLENWENNS|NB_SI_MULTIPLE|CONTA_SE_MULTIPLO
AVERAGEIFS|MITTELWERTWENNS|MOYENNE_SI_MULTIPLE|MEDIA_SE_MULTIPLO
INDEX|INDEX|INDEX|INDICE
MATCH|VERGLEICH|EQUIV|CONFRONTA
XMATCH|XVERGLEICH|EQUIV_X|CONFRONTA_X
VLOOKUP|SVERWEIS|RECHERCHE_V|CERCA_VERT
HLOOKUP|WVERWEIS|RECHERCHE_H|CERCA_ORIZZ
XLOOKUP|XVERWEIS|RECHERCHE_X|CERCA_X
LOOKUP|VERWEIS|RECHERCHE|CERCA_VETTORE
FILTER|FILTERN|FILTRER|FILTRA
UNIQUE|EINDEUTIG|UNIQUE|UNICI
SORT|SORTIEREN|TRIER|ORDINA
SEQUENCE|SEQUENZ|SÉQUENCE|SEQUENZA
TEXTSPLIT|TEXTTEILEN|SCINDER_TEXTE|DIVIDI_TESTO
PARSE|LESEN|LIRE|LEGGI
REGEXP_EXTRACTALL|REGEX_ALLE|REGEX_EXTRAIRE_TOUT|REGEX_ESTRAI_TUTTO
GROUPBY|GRUPPIEREN|GROUPER|RAGGRUPPA
UNPIVOT|ENTPIVOTIEREN|DÉPIVOTER|ANNULLA_PIVOT
TABLE|TABELLE|TABLEAU|TABELLA
JOIN|VERKNÜPFEN|JOINDRE|COLLEGA
CHOOSECOLS|SPALTENWAHL|CHOISIR_COLONNES|SCEGLI_COLONNE
CHOOSEROWS|ZEILENWAHL|CHOISIR_LIGNES|SCEGLI_RIGHE
TAKE|NEHMEN|PRENDRE|PRENDI
DROP|WEGLASSEN|RETIRER|SCARTA
TOCOL|ZUSPALTE|EN_COLONNE|IN_COLONNA
TOROW|ZUZEILE|EN_LIGNE|IN_RIGA
FREQUENCY|HÄUFIGKEIT|FRÉQUENCE|FREQUENZA
TRANSPOSE|TRANSPONIEREN|TRANSPOSER|TRASPONI
ROWS|ZEILEN|LIGNES|RIGHE
COLUMNS|SPALTEN|COLONNES|COLONNE
HSTACK|HSTAPELN|EMPILER_H|IMPILA_ORIZZ
VSTACK|VSTAPELN|EMPILER_V|IMPILA_VERT
SUMPRODUCT|SUMMENPRODUKT|SOMMEPROD|MATR_SOMMA_PRODOTTO
LET|LET|SOIT|SIA
LAMBDA|LAMBDA|LAMBDA|LAMBDA
MAP|ABBILDEN|APPLIQUER|APPLICA
REDUCE|REDUZIEREN|RÉDUIRE|RIDUCI
SCAN|ZWISCHENWERTE|CUMULER|ACCUMULA
BYROW|NACHZEILE|PAR_LIGNE|PER_RIGA
PIVOT|PIVOT|PIVOT|PIVOT
MAKEARRAY|ARRAY_ERSTELLEN|CRÉER_MATRICE|CREA_MATRICE
ENCODEURL|URL_KODIEREN|ENCODER_URL|CODIFICA_URL
DECODEURL|URL_DEKODIEREN|DÉCODER_URL|DECODIFICA_URL
EDATE|MONATE_VERSCHIEBEN|DÉCALER_MOIS|SPOSTA_MESI
EOMONTH|MONATSENDE|FIN_MOIS|FINE_MESE
WEEKDAY|WOCHENTAG|JOUR_SEMAINE|GIORNO_SETTIMANA
WEEKNUM|KALENDERWOCHE|NUM_SEMAINE|NUM_SETTIMANA
ISOWEEKNUM|ISO_KALENDERWOCHE|ISO_NUM_SEMAINE|ISO_NUM_SETTIMANA
DATE|DATUM|DATE|DATA
ISOWEEKYEAR|ISO_WOCHENJAHR|ISO_ANNÉE_SEMAINE|ISO_ANNO_SETTIMANA
DATEDIF|VOLLE_DATUMSDIFFERENZ|DIFF_DATE_COMPLÈTE|DIFF_DATA_COMPLETA
NETWORKDAYS|NETTOARBEITSTAGE|JOURS_OUVRÉS|GIORNI_LAVORATIVI
INTL|INDIVIDUELL|PERSONNALISÉ|PERSONALIZZATO
WORKDAY|ARBEITSTAG|JOUR_OUVRÉ|GIORNO_LAVORATIVO
ADD|ADDIEREN|AJOUTER|AGGIUNGI
DIFF|DIFFERENZ|DIFFÉRENCE|DIFFERENZA
ISO|ISO|ISO|ISO
FORMAT|FORMAT|FORMAT|FORMATO
TIMESTAMP|ZEITSTEMPEL|HORODATAGE|TIMESTAMP
FROMTIMESTAMP|AUS_ZEITSTEMPEL|DEPUIS_HORODATAGE|DA_TIMESTAMP
ISLEAP|ISTSCHALTJAHR|EST_BISSEXTILE|È_BISESTILE
TIME|ZEIT|HEURE|ORA
TIMEVALUE|ZEITWERT|VALEUR_HEURE|VALORE_ORA
DURATION|DAUER|DURÉE|DURATA
COLOR|FARBE|COULEUR|COLORE
RGB|RGB|RGB|RGB
HSL|HSL|HSL|HSL
HEX|HEX|HEX|HEX
RED|ROT|ROUGE|ROSSO
GREEN|GRÜN|VERT|VERDE
BLUE|BLAU|BLEU|BLU
HUE|FARBTON|TEINTE|TONALITÀ
SATURATION|SÄTTIGUNG|SATURATION|SATURAZIONE
LIGHTNESS|HELLIGKEIT|CLARTÉ|LUMINOSITÀ
MIX|MISCHEN|MÉLANGER|MISCELA
LIGHTEN|AUFHELLEN|ÉCLAIRCIR|SCHIARISCI
DARKEN|ABDUNKELN|ASSOMBRIR|SCURISCI
INVERT|INVERTIEREN|INVERSER|INVERTI
COMPLEMENT|KOMPLEMENT|COMPLÉMENT|COMPLEMENTARE
LUMINANCE|LEUCHTDICHTE|LUMINANCE|LUMINANZA
CONTRAST|KONTRAST|CONTRASTE|CONTRASTO
PALETTE|PALETTE|PALETTE|PALETTA
TODAY|HEUTE|AUJOURDHUI|OGGI
NOW|JETZT|MAINTENANT|ADESSO
YEAR|JAHR|ANNÉE|ANNO
MONTH|MONAT|MOIS|MESE
DAY|TAG|JOUR|GIORNO
HOUR|STUNDE|HEURES|ORE
MINUTE|MINUTE|MINUTE|MINUTO
SECOND|SEKUNDE|SECONDE|SECONDO
DATEVALUE|DATUMWERT|VALEUR_DATE|VALORE_DATA
DAYS|TAGE|JOURS|GIORNI
PI|PI|PI|PI
EXP|EXP|EXP|EXP
LN|LN|LN|LN
LOG|LOG|LOG|LOG
LTRIM|LINKS_KÜRZEN|ÉLAGUER_GAUCHE|TAGLIA_SINISTRA
RTRIM|RECHTS_KÜRZEN|ÉLAGUER_DROITE|TAGLIA_DESTRA
TRIM|KÜRZEN|ÉLAGUER|TAGLIA
SQUEEZE|LEERRAUM_GLÄTTEN|RÉDUIRE_ESPACES|RIDUCI_SPAZI
SUBSTR|TEILTEXT|SOUS_CHAÎNE|SOTTOSTRINGA
REVERSE|UMKEHREN|INVERSER_TEXTE|INVERTI_TESTO
REPEAT|WIEDERHOLEN|RÉPÉTER|RIPETI
STARTSWITH|BEGINNTMIT|COMMENCE_PAR|INIZIA_CON
ENDSWITH|ENDETMIT|FINIT_PAR|FINISCE_CON
CONTAINS|ENTHÄLT|CONTIENT|CONTIENE
SPLIT|TEILEN|SCINDER|DIVIDI
REPLACEALL|ALLE_ERSETZEN|TOUT_REMPLACER|SOSTITUISCI_TUTTO
PADSTART|LINKS_AUFFÜLLEN|COMPLÉTER_GAUCHE|RIEMPI_SINISTRA
PADEND|RECHTS_AUFFÜLLEN|COMPLÉTER_DROITE|RIEMPI_DESTRA
REGEXP|REGEX_TEST|REGEX_TEST|REGEX_TEST
REGEXP_EXTRACT|REGEX_EXTRAHIEREN|REGEX_EXTRAIRE|REGEX_ESTRAI
REGEXP_REPLACE|REGEX_ERSETZEN|REGEX_REMPLACER|REGEX_SOSTITUISCI
REGEXP_SPLIT|REGEX_TEILEN|REGEX_SCINDER|REGEX_DIVIDI
GEO|GEO|GÉO|GEO
DISTANCE|ABSTAND|DISTANCE|DISTANZA
BEARING|PEILUNG|CAP|DIREZIONE
DESTINATION|ZIEL|DESTINATION|DESTINAZIONE
GEOM|GEOMETRIE|GÉOMÉTRIE|GEOMETRIA
CIRCLE|KREIS|CERCLE|CERCHIO
AREA|FLÄCHE|AIRE|AREA
CIRCUMFERENCE|UMFANG|CIRCONFÉRENCE|CIRCONFERENZA
RECTANGLE|RECHTECK|RECTANGLE|RETTANGOLO
TRIANGLE|DREIECK|TRIANGLE|TRIANGOLO
SPHERE|KUGEL|SPHÈRE|SFERA
VOLUME|VOLUMEN|VOLUME|VOLUME
POLYGON|POLYGON|POLYGONE|POLIGONO
PERIMETER|RANDLÄNGE|PÉRIMÈTRE|PERIMETRO
HASH|HASH|HACHAGE|HASH
SHA256|SHA256|SHA256|SHA256
FNV1A|FNV1A|FNV1A|FNV1A
CRC32|CRC32|CRC32|CRC32
RANDOM|ZUFALL|ALÉATOIRE|CASUALE
INT|GANZZAHL|ENTIER|INTERO
SEEDED|MIT_STARTWERT|INITIALISÉ|CON_SEME
NORMAL|NORMALVERTEILT|NORMAL|NORMALE
UUID|UUID|UUID|UUID
RADIANS|BOGENMASS|RADIANS|RADIANTI
DEGREES|GRAD|DEGRÉS|GRADI
SIN|SIN|SIN|SEN
COS|COS|COS|COS
TAN|TAN|TAN|TAN
ASIN|ARCSIN|ASIN|ARCSEN
ACOS|ARCCOS|ACOS|ARCCOS
ATAN|ARCTAN|ATAN|ARCTAN
ATAN2|ARCTAN2|ATAN2|ARCTAN2
HYPOT|HYPOT|HYPOT|IPOTENUSA
JSON|JSON|JSON|JSON
STRINGIFY|SERIALISIEREN|SÉRIALISER|SERIALIZZA
VALID|GÜLTIG|VALIDE|VALIDO
TYPE|TYP|TYPE|TIPO
GET|ABRUFEN|OBTENIR|OTTIENI
HAS|HAT|CONTIENT_CHEMIN|HA
KEYS|SCHLÜSSEL|CLÉS|CHIAVI
VALUES|WERTE|VALEURS|VALORI
ENTRIES|EINTRÄGE|ENTRÉES|VOCI
LENGTH|LÄNGE|LONGUEUR|LUNGHEZZA
SET|SETZEN|DÉFINIR|IMPOSTA
REMOVE|ENTFERNEN|SUPPRIMER|RIMUOVI
MERGE|ZUSAMMENFÜHREN|FUSIONNER|UNISCI
OBJECT|OBJEKT|OBJET|OGGETTO
ARRAY|ARRAY|MATRICE|MATRICE
FROMTABLE|AUS_TABELLE|DEPUIS_TABLEAU|DA_TABELLA
FLATTEN|ABFLACHEN|APLATIR|APPIATTISCI
CSV|CSV|CSV|CSV
WEB|WEB|WEB|WEB
STATUS|STATUS|STATUT|STATO
MANDELBROT|MANDELBROT|MANDELBROT|MANDELBROT
`;
const words = new Map(
  translations
    .trim()
    .split("\n")
    .map((row) => {
      const [en, de, fr, it] = row.split("|");
      return [en, { en, de, fr, it }];
    }),
);
export const formulaLanguages = Object.freeze(["de", "en", "fr", "it"]);
export function formulaLanguage(language = "en") {
  const code = String(language).toLowerCase().split(/[-_]/)[0];
  return formulaLanguages.includes(code) ? code : "en";
}
export function normalizeFormulaName(name) {
  if (typeof name !== "string")
    throw new TypeError("Formula function names must be strings");
  const normalized = name
    .trim()
    .replace(/^=/, "")
    .normalize("NFC")
    .toUpperCase();
  if (
    !/^[\p{L}_][\p{L}\p{M}0-9_]*(?:\.[\p{L}_][\p{L}\p{M}0-9_]*)*$/u.test(
      normalized,
    )
  )
    throw new TypeError(`Invalid formula function name: ${name}`);
  return normalized;
}
// Accent-free input is accepted for phone keyboards; collisions fail at startup.
const key = (name) =>
  normalizeFormulaName(name).normalize("NFD").replace(/\p{M}/gu, "");
const records = new Map(),
  aliases = new Map();
function category(id) {
  if (id === "MANDELBROT") return "OPTIONAL";
  if (id.includes(".")) return id.split(".")[0];
  if (
    /^(TODAY|NOW|DATE|YEAR|MONTH|DAY|EDATE|EOMONTH|WEEK|ISOWEEK|NETWORKDAYS|WORKDAY)/.test(
      id,
    )
  )
    return "DATE";
  if (/^(TIME|HOUR|MINUTE|SECOND)/.test(id)) return "TIME";
  if (
    [
      "IF",
      "IFS",
      "SWITCH",
      "CHOOSE",
      "IFERROR",
      "IFNA",
      "AND",
      "OR",
      "XOR",
      "NOT",
      "TRUE",
      "FALSE",
      "LET",
      "LAMBDA",
    ].includes(id)
  )
    return "LOGIC";
  if (/^(IS|N$|VALUE$)/.test(id)) return "TYPE";
  if (/(LOOKUP|MATCH|INDEX)/.test(id)) return "LOOKUP";
  if (
    [
      "FILTER",
      "UNIQUE",
      "SORT",
      "SEQUENCE",
      "TEXTSPLIT",
      "GROUPBY",
      "UNPIVOT",
      "CHOOSECOLS",
      "CHOOSEROWS",
      "TAKE",
      "DROP",
      "TOCOL",
      "TOROW",
      "FREQUENCY",
      "TRANSPOSE",
      "ROWS",
      "COLUMNS",
      "HSTACK",
      "VSTACK",
      "SUMPRODUCT",
      "MAP",
      "REDUCE",
      "SCAN",
      "BYROW",
      "PIVOT",
      "MAKEARRAY",
    ].includes(id)
  )
    return "ARRAY";
  if (/^(SUM|AVERAGE|MIN$|MAX$|MEDIAN|LARGE|SMALL|COUNT)/.test(id))
    return "STAT";
  if (
    [
      "ABS",
      "ROUND",
      "ROUNDUP",
      "ROUNDDOWN",
      "FLOOR",
      "CEIL",
      "SQRT",
      "POW",
      "MOD",
      "SIGN",
      "PI",
      "EXP",
      "LN",
      "LOG",
      "RADIANS",
      "DEGREES",
      "SIN",
      "COS",
      "TAN",
      "ASIN",
      "ACOS",
      "ATAN",
      "ATAN2",
      "HYPOT",
    ].includes(id)
  )
    return "MATH";
  return "TEXT";
}
const extras = `WEB.GET|url|Liest eine HTTPS-Antwort als Text; nur in der App nach Aktivierung.|Reads HTTPS response text; app only, after enabling.
WEB.JSON|url; path?|Liest HTTPS-JSON, optional einen Pfad; nur in der App.|Reads HTTPS JSON, optionally a path; app only.
WEB.STATUS|url|HTTP-Status der HTTPS-Antwort; nur in der App.|HTTP status of the HTTPS response; app only.`;
for (const row of (formulaHelpRows.trim() + "\n" + extras).split("\n")) {
  const [names, args, de, en] = row.split("|");
  for (const name of names.split("/")) {
    const id = legacy[name] ?? name;
    if (records.has(id)) continue;
    const localized = Object.fromEntries(
      formulaLanguages.map((language) => [
        language,
        id
          .split(".")
          .map((segment) => {
            if (!words.has(segment))
              throw new Error(`Missing translation: ${segment}`);
            return words.get(segment)[language];
          })
          .join("."),
      ]),
    );
    const signatureArgs = id === "COUNTIF" ? "range; criteria" : args;
    const params = signatureArgs
        .split(";")
        .map((value) => value.trim())
        .filter(Boolean),
      variadic = params.some((value) => value.includes("…"));
    const arity = Object.freeze({
      min:
        id === "JSON.OBJECT"
          ? 1
          : params.filter(
              (value) =>
                !value.includes("…") &&
                !value.includes("?") &&
                !value.includes("="),
            ).length,
      max: variadic ? Infinity : params.length,
    });
    records.set(id, {
      id,
      names: Object.freeze(localized),
      args: signatureArgs,
      arity,
      volatile: [
        "TODAY",
        "NOW",
        "RANDOM",
        "RANDOM.INT",
        "RANDOM.NORMAL",
        "RANDOM.UUID",
      ].includes(id),
      descriptions: Object.freeze({ de, en }),
      category: category(id),
      availability: id.startsWith("WEB.")
        ? "app"
        : id === "MANDELBROT"
          ? "optional"
          : "core",
      evaluation: [
        "IF",
        "IFS",
        "SWITCH",
        "IFERROR",
        "IFNA",
        "AND",
        "OR",
        "LET",
        "LAMBDA",
        "PIVOT",
      ].includes(id)
        ? "special"
        : "eager",
      aliases: [],
    });
  }
}
for (const record of records.values()) {
  const names = new Set([
    record.id,
    ...Object.values(record.names),
    ...Object.keys(legacy).filter((name) => legacy[name] === record.id),
  ]);
  for (const name of names) {
    const normalized = key(name),
      previous = aliases.get(normalized);
    if (previous && previous !== record.id)
      throw new Error(
        `Formula alias collision: ${name} (${previous}, ${record.id})`,
      );
    aliases.set(normalized, record.id);
  }
  record.aliases = Object.freeze([...names]);
  Object.freeze(record);
}
export const formulaCatalog = Object.freeze([...records.values()]);
export function resolveFormulaName(name) {
  const normalized = normalizeFormulaName(name);
  return aliases.get(key(normalized)) ?? normalized;
}
export function formulaDefinition(name) {
  return records.get(resolveFormulaName(name));
}
export function localizedFormulaName(name, language = "en") {
  const record = formulaDefinition(name);
  return record?.names[formulaLanguage(language)] ?? normalizeFormulaName(name);
}
